ALTER TABLE users ADD COLUMN total_storage_bytes BIGINT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN file_count INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN max_storage_bytes BIGINT NOT NULL DEFAULT 104857600;
ALTER TABLE users ADD COLUMN max_file_count INT NOT NULL DEFAULT 500;
ALTER TABLE users ADD COLUMN is_demo BOOLEAN NOT NULL DEFAULT FALSE;